image: thecodingmachine/php:8.2-v4-cli-node20

stages:
  - caching
  - testing

variables:
  TRIGGER_CACHE: "off"
  
## règles du pipeline total
## utilisation d'une variables d'environnements prédéfinies
## https://docs.gitlab.com/ci/variables/predefined_variables/
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"


generate_deps:
  stage: caching
  tags:
    - formation
  script:
    - cd project
    - composer install
  cache:
    key: deps
    policy: push
    paths:
      - project/vendor
  rules:
    - changes:
        - project/composer.json
    - if: $TRIGGER_CACHE == "on" # /[]{2}.*$/
      when: on_success



test:
  stage: testing
  tags:
    - formation
  script:
    - cd project
    - php ./vendor/bin/phpunit --log-junit=test.xml tests
  artifacts:
    when: always
    expire_in: "1 hour"
    reports:
      junit: project/test.xml
  cache:
    key: deps
    untracked: true
    policy: pull
    
    # utilisation du registre de package générique
    # pour hoster les jeu de donées volumineux
    # https://archives.docs.gitlab.com/17.7/ee/user/packages/generic_packages/index.html#publish-a-package
    # - curl $CI_JOB_TOKEN https://gitlan/lan.fr/..../package/generic/data.csv -o fixture.csv
  