image: "$CI_REGISTRY_IMAGE/python:rc-slim-buster"

variables:
  TRIGGER_CACHE: "off"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - tests

# génération des dépendances projet
create_env:
  stage: .pre
  before_script:
    # création du dossier de dépendances "venv"
    - python3 -m venv venv
    # activation de l'environnement virtuel
    - source venv/bin/activate
  script:
    # installation des dépendances dans l'environnement virtuel
    - pip3 install -r requirements.txt
  cache:
    key: venv
    paths:
      - venv
    policy: push
  rules:
    # déclenchement auto
    - changes:
        - requirements.txt
    # déclenchement manuel
    - if: $TRIGGER_CACHE == "on"

test:
  stage: tests
  script:
    - source venv/bin/activate
    - python3 coverage_tests.py
    - ls -al reports
  cache:
    key: venv
    untracked: true
    policy: pull


  


