workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

image: python:3.11.10-slim-bookworm

stages:
  - init
  - testing
  - quality
  - deploy
  - e2e


# "." => désactive le job
generate-deps:
  stage: init
  tags: [myusine]
  script:
    - python3 -m venv ./venv
    - source ./venv/bin/activate
    - pip3 install -r app/requirements.txt
    - pip3 install -r app/requirements-dev.txt
  variables:
    TRIGGER_CACHE: "on"
  cache:
    key: virtual-env 
    paths:
      - ./venv
    policy: push
  rules:
    - changes: 
        - app/requirements.txt
        - app/requirements-dev.txt
    - if: $TRIGGER_CACHE == "off"
      when: on_success

.test:
  stage: testing
  tags:
    - myusine
  script:
    - source ./venv/bin/activate
    - cd app
    # ">" opérateur YAML qui convertie \n en " "
    - >
      pytest 
      --junit-xml=./units.xml 
      --cov=bank 
      --cov-report=term 
      --cov-report=xml:coverage.xml
  # détection de la couverture globale dans la sortie du job => rerpot=term / avec une regex
  coverage: "/^TOTAL.*?([0-9]{1,3})%/"
  cache:
    key: virtual-env
    untracked: true
    policy: pull
  artifacts:
    expire_in: "1 hour"
    paths:
      - ./app/units.xml
      - ./app/coverage.xml
    reports:
      junit: ./app/units.xml
      coverage_report:
        coverage_format: cobertura
        path: ./app/coverage.xml

.sonar:
  # désactivation de la commande de base (entrypoint) de l'image, au profit de notre "script:" 
  image:
    name: sonarsource/sonar-scanner-cli:11
    entrypoint: [""]
  tags:
    - myusine
  stage: quality
  # utiliser des variables cachées dans Gitlab CI
  # 1. projet -> settings -> CICD -> Variables
  # créer une variable: cachée + masquée et non protégée (pour toutes les branches)
  # donner le nom et la valeur
  script:
    - >
      sonar-scanner
      -Dsonar.projectKey=myusine
      -Dsonar.sources=./app
      -Dsonar.exclusions=./app/venv
      -Dsonar.host.url=http://$SONAR_HOST:9000
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.python.coverage.reportPaths=./app/coverage.xml
      -Dsonar.qualitygate.wait=true

.deploy:
  tags:
    - myusine
  stage: deploy
  script:
    - echo "DEPLOY !!"
  ## ajoute un lien vers l'application déployée !!!
  ## possibilité d'environnement Dynamiques
  environment:
    name: staging
    url: http://192.168.44.180:8080
  # le job n'est exécutable qu'avec un tag
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
    # - if: $CI_COMMIT_TAG ~= /^v\.\d+/

e2e:
  tags:
    - myusine
  stage: e2e
  services:
    - name: selenium/standalone-firefox:latest
      # dns du serveur => dans la config client
      alias: selenium-server
  script:
    - source ./venv/bin/activate
    # le client selenium a besoin du driver du moteur du navigateur ivi gecko => firefox
    - mv geckodriver /usr/bin/geckodriver
    - chmod +x /usr/bin/geckodriver
    - cd app
    # filtrer des tests selon un marqueur
    - pytest -m e2e
  cache:
    key: virtual-env
    untracked: true
    policy: pull
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  