#!/bin/bash

cp_with_subdir(){
  for path in $@
  do
    parent=$(dirname $path)
    if [ "$parent" = "." ]; then cp $path "../workdir/samples/$path"
    else
      mkdir -p "../workdir/samples/$parent"
      cp $path "../workdir/samples/$parent/$path"
    fi
  done
}

if [[ -d "../workdir" ]]; then
  if [[ ! -d "../workdir/samples" ]]; then
    mkdir ../workdir/samples
  fi
  last_commit=$(git rev-list --all -1)
  last_commit=${last_commit:0:7}
  last_commit_main=$(git log -1 --oneline main | awk '{print $1}')
  if [[ "$last_commit" == "$last_commit_main" ]]; then
    last_commit_origin_main=$(git log -1 --oneline origin/main | awk '{print $1}')
    if [[ "$last_commit_main" == "$last_commit_origin_main" ]]; then
      # git log -1 --stat=200 main | grep -Po "^ \K[a-zA-Z0-9\._/-]+(?= +\|)" | xargs -i cp {} ../workdir/samples
      git log -1 --stat=200 main | grep -Po "^ \K[a-zA-Z0-9\._/-]+(?= +\|)" | xargs cp_with_subdir
    fi
  fi
fi